import { chromium } from "@playwright/test";
import { createClient } from "@supabase/supabase-js";
import { BASE_URL, storageStatePath } from "../config.ts";
const CLIENT_ID = "c2379d1b-a8b9-4966-9efa-073dcb3f881e";
const browser = await chromium.launch();
const ctx = await browser.newContext({ storageState: storageStatePath("admin") });
const page = await ctx.newPage();
page.on("console", m => { if (m.type() === "error") console.log("console:", m.text().slice(0, 200)); });
await page.goto(`${BASE_URL}/clients/${CLIENT_ID}/edit`, { waitUntil: "networkidle" });
console.log("url:", page.url());
const btn = page.locator("button", { hasText: "Save BL profile" });
console.log("save buttons:", await btn.count());
await btn.click();
await page.waitForTimeout(4000);
const body = await page.evaluate(() => document.body.innerText);
console.log("Saved marker:", body.includes("Saved"));
const err = body.match(/(Failed[^\n]*|error[^\n]{0,120})/i);
console.log("error text:", err?.[0] ?? "(none)");
await browser.close();
const sb = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!.trim(), process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!.trim(), { auth: { persistSession: false } });
await sb.auth.signInWithPassword({ email: process.env.E2E_OPERATION_EMAIL!, password: process.env.E2E_PASSWORD! });
const { data } = await sb.from("events").select("created_at, event_type").in("event_type", ["po.docs_requirements_requested", "po.docs_requirements_resolved"]).order("created_at", { ascending: false }).limit(4);
console.log(JSON.stringify(data, null, 1));
